version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  mysqlservice:
    image: mysql:latest
    container_name: mysql
    restart: always
    hostname: localhost
    network_mode: "host"
    ports:
      - 3306:3306
      #    cap_add:
      #      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'Password'
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017
