
  port:8080
spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  cloud:
    gateway:
      routes:
        - id: EMAIL-SERVICE
          uri:
            lb://EMAIL-SERVICE
          predicates:
            - path= /EmailService/**