server:
  port:8080
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: email-service
          uri: http://localhost:8081
          predicates:
             - Path=/email-service/**
          filters:
              - RewritePath=/email-service(?<segment>/?.*), $\{segment}