server:
  port: 8080

spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
      routes:
        - id:
          uri:
            lb://
          predicates:
            - path=/api/v1/**